apiVersion: apps/v1
kind: Deployment
metadata:
  name: techieglobus
 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
    
  template:
    metadata:
      name: apache
      labels:
        app: dev
    spec:
      containers:
      - image: httpd
        name: techi
        volumeMounts:
          - name: data
            mountPath: /usr/local/apache2/htdocs/
       
    volumes:
      - name: data
        emptyDir: {}

